#!/usr/bin/env bash
#
# MUON real-vendor campaign — disposable golden-task repo scaffold.
#
# Creates a tiny, throwaway git repository with a couple of source files and
# ONE intentionally failing test, suitable as the target workspace for a real
# Claude/Codex "golden task" dispatch (see scripts/real-vendor-campaign.sh and
# docs/testing/real-vendor-campaign.md). No npm dependencies are installed —
# the failing test uses Node's built-in `node:test` runner — so this scaffold
# works fully offline and finishes in well under a second.
#
# This script NEVER touches your real MUON data dir, never reads/writes
# credentials, and never runs as root. It only writes files under the target
# directory (default: a fresh mktemp dir) and runs `git` scoped to that
# directory with a LOCAL (not global) author identity.
#
# Usage:
#   scripts/make-disposable-repo.sh [--dir <path>] [--force]
#
#   --dir <path>   Where to scaffold the repo (default: a fresh mktemp dir
#                   under $TMPDIR, printed on completion).
#   --force        Reuse --dir even if it already exists and is non-empty
#                   (existing content is left alone; MUON files are added/
#                   overwritten). Without --force, a non-empty --dir aborts.
#
# On success, the LAST line of stdout is exactly:
#   REPO_PATH=<absolute path>
# so callers (including real-vendor-campaign.sh) can capture it with:
#   REPO_PATH="$(scripts/make-disposable-repo.sh --dir "$X" | tail -1 | cut -d= -f2-)"

set -euo pipefail

if [ "$(id -u)" = "0" ]; then
  echo "ERROR: refusing to run as root." >&2
  exit 1
fi

DIR=""
FORCE=0

usage() {
  sed -n '2,29p' "$0" | sed 's/^# \{0,1\}//'
}

while [ $# -gt 0 ]; do
  case "$1" in
    --dir)
      DIR="${2:-}"
      shift 2
      ;;
    --force)
      FORCE=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "ERROR: unknown argument '$1'." >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [ -z "$DIR" ]; then
  DIR="$(mktemp -d "${TMPDIR:-/tmp}/muon-golden-repo.XXXXXX")"
else
  if [ -e "$DIR" ] && [ -n "$(ls -A "$DIR" 2>/dev/null)" ] && [ "$FORCE" -ne 1 ]; then
    echo "ERROR: '$DIR' already exists and is non-empty. Pass --force to reuse it, or pick another --dir." >&2
    exit 1
  fi
  mkdir -p "$DIR"
fi

# Resolve to an absolute, symlink-free path so downstream scripts never have
# to guess (matches the pattern MUON's own worktree helpers rely on).
DIR="$(cd "$DIR" && pwd -P)"

echo "Scaffolding a disposable golden-task repo at: $DIR" >&2

cat > "$DIR/package.json" <<'EOF'
{
  "name": "muon-golden-task-repo",
  "private": true,
  "type": "module",
  "description": "Disposable scratch repo for a MUON real-vendor golden-task dispatch. Safe to delete at any time.",
  "scripts": {
    "test": "node --test"
  }
}
EOF

mkdir -p "$DIR/src" "$DIR/test"

# The bug: greet() drops the name instead of interpolating it. A correct,
# minimal, additive fix is exactly the shape of task a real agent should
# handle cleanly in one pass.
cat > "$DIR/src/greet.js" <<'EOF'
/**
 * Return a friendly greeting for `name`.
 *
 * NOTE for the agent: this currently drops the name. Fix it so
 * greet("MUON") === "Hello, MUON!" — additive/minimal diff only, and keep
 * the existing exported signature.
 */
export function greet(name) {
  return "Hello, !";
}
EOF

cat > "$DIR/test/greet.test.js" <<'EOF'
import { test } from "node:test";
import assert from "node:assert/strict";
import { greet } from "../src/greet.js";

test("greet() includes the given name", () => {
  assert.equal(greet("MUON"), "Hello, MUON!");
});

test("greet() works for a different name too", () => {
  assert.equal(greet("world"), "Hello, world!");
});
EOF

cat > "$DIR/README.md" <<'EOF'
# MUON golden-task scratch repo

This is a **disposable** repository generated by
`scripts/make-disposable-repo.sh` for MUON's real-vendor E2E campaign
(`scripts/real-vendor-campaign.sh`, `docs/testing/real-vendor-campaign.md`).

It contains one intentionally failing test:

```bash
npm test    # or: node --test
```

The golden task is: fix `src/greet.js` so both tests in
`test/greet.test.js` pass, with an additive/minimal diff.

Safe to delete this entire directory at any time; nothing outside it depends
on this repo's contents.
EOF

cat > "$DIR/.gitignore" <<'EOF'
node_modules/
.muon/
EOF

cd "$DIR"
if [ ! -d ".git" ]; then
  git init -q
fi
# LOCAL-only identity — never touches the caller's global git config.
git config --local user.email "muon-golden-task@example.invalid"
git config --local user.name "MUON Golden Task Repo"
git add -A
if ! git diff --cached --quiet; then
  git commit -q -m "chore: disposable golden-task baseline (intentionally failing test)"
else
  echo "(nothing new to commit — scaffold already matches this baseline)" >&2
fi

echo "" >&2
echo "Baseline sanity check (this SHOULD fail — that is the point):" >&2
set +e
node --test 2>&1 | tail -n 20 >&2
TEST_EXIT=$?
set -e
if [ "$TEST_EXIT" -eq 0 ]; then
  echo "WARNING: the baseline test unexpectedly passed. The scaffold may be stale; regenerate with --force." >&2
else
  echo "✓ baseline test fails as expected (exit $TEST_EXIT) — a real golden task for the agent." >&2
fi

echo "" >&2
echo "Add this repo to MUON's workspace allowlist before dispatching into it:" >&2
echo "  export MUON_WORKSPACE_ROOTS=\"$DIR\"" >&2
echo "  # to allow multiple roots: MUON_WORKSPACE_ROOTS=\"$DIR:\$OTHER_DIR\"" >&2
echo "" >&2
echo "Suggested golden-task brief:" >&2
echo "  \"Fix the failing test in test/greet.test.js by completing src/greet.js's" >&2
echo "   greet(name) function so it returns the full greeting. Additive/minimal" >&2
echo "   diff only.\"" >&2
echo "" >&2

echo "REPO_PATH=$DIR"
